name: Jira Issue

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      project:
        type: string
        description: Jira Project Key
        required: true
      issue_type:
        type: string
        description: Type of Jira issue
        default: Bug
      codeql_alert_id:
        type: string
        description: CodeQL Scan Alert ID
        required: true
      codeql_alert_name:
        type: string
        description: CodeQL Scan Alert Name
        required: true
      codeql_alert_url:
        type: string
        description: CodeQL Scan Alert URL
        required: true
      codeql_alert_severity:
        type: string
        description: CodeQL Scan Alert Severity
        required: true

jobs:
  create_issue:
    runs-on: ubuntu-latest
    name: Jira Example
  
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: ${{ inputs.project }}
        issuetype: ${{ inputs.issue_type }}
        summary: 'CodeQL Vulnerability (${{ inputs.codeql_alert_severity }}): ${{ inputs.codeql_alert_name }}'
        description: 'CodeQL scan alert "${{ inputs.codeql_alert_name }}" found in ${{ inputs.codeql_alert_url }}'
        # fields: '{"customfield_10043": 102}'
        fields: '{"customfield_10043": ${{ fromJSON(inputs.codeql_alert_id) }}}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"        
