on:
  workflow_dispatch:
  push:
    paths:
      - '**/create-jira-ticket.yml'

name: Create Jira Ticket

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

  create:
    uses: ./.github/workflows/jira-issue.yml
    with:
      project: STP
      summary: Test bugs
      description: GitHub issue bugs
  
  display:
    runs-on: ubuntu-latest
    steps:
    - name: Log created issue
      run: echo "Issue ${{ jobs.create.outputs.issue }} was created"        
