on:
  workflow_dispatch:
  push:
    paths:
      - '**/create-jira-ticket.yml'

name: Create Jira Ticket

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: STP
        issuetype: Bug
        summary: Test bug
        description: GitHub issue bug
        # fields: '{"customfield_10171": "test"}'
    
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
