name: .NET

on:
  push:
    branches: 
      - 'main'
    paths-ignore:
      - '**.ql'
      - 'README.MD'
      - '**/codeql.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      # working-directory: sample1/
      run: docker build .    
