on:
  workflow_call:
  workflow_dispatch:
  push:
    paths: '**/get-github-issue-details.yml'

name: Get GitHub issue details

# env:
#   GH_TOKEN: ${{ github.token }}

permissions:
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-issue-json.outputs.json_data }}
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Execute python script
      id: get-issue-json
      run: |
        output=$(python ./.github/scripts/github-issues.py)
        echo "json_data=${output}" >> $GITHUB_OUTPUT

  create:
    needs: build
    uses: ./.github/workflows/create-jira-issue.yml
    strategy:
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}
      fail-fast: true
    with:
      project: STP
      summary: ${{ matrix['include'].title }}
      description: ${{ matrix['include'].body }}
    secrets: inherit
