name: GitHub Issue Jira Mapping

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      project:
        type: string
        description: Jira Project Key
        required: true
      issue_type:
        type: string
        description: Type of Jira issue
        default: Bug
      github_issue_id:
        type: string
        description: GitHub Issue ID
        required: true
      github_issue_name:
        type: string
        description: GitHub Issue Name
        required: true
      github_issue_url:
        type: string
        description: GitHub Issue URL
        required: true

jobs:
  create_issue:
    runs-on: ubuntu-latest
    name: GitHub-Jira
  
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: ${{ inputs.project }}
        issuetype: ${{ inputs.issue_type }}
        summary: 'GitHub Issue: ${{ inputs.github_issue_name }}'
        description: 'GitHub Issue "${{ inputs.github_issue_name }}" found in ${{ inputs.github_issue_url }}'
        fields: '{"customfield_10044": ${{ fromJSON(inputs.github_issue_id) }}}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"        
