name: Jira Issue

on: 
  workflow_call:
    inputs:
      project:
        type: string
        description: Jira Project Key
        required: true
      type:
        type: string
        description: Type of Jira issue
        default: Bug
      # summary:
      #   type: string
      #   description: Issue summary
      #   required: true
      # description:
      #   type: string
      #   description: Issue description
      #   required: true
    
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  create_issue:
    strategy:
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}
    runs-on: ubuntu-latest
    name: Jira Example
    
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: ${{ inputs.project }}
        issuetype: ${{ inputs.type }}
        # summary: ${{ inputs.summary }}
        # description: ${{ inputs.description }}
        summary: ${{ matrix.title }}
        description: ${{ matrix.body }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"        
