name: Create GitHub Issue

on: workflow_call
  # push:
  #   branches: 
  #     - 'main'
  #   paths:
  #     - '**/test-api.yml'
  #     - '**.sh'
      
env:
    GH_TOKEN: ${{ github.token }}

permissions:
  issues: write
  security-events: read
  actions: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Run script to create GitHub Issues for CodeQL Scan Vulnerabilities
      run: bash ./github/scripts/myscript.sh
