# write a github actions yaml script to echo hello world

name: Lint, Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Publish file name
      run: find .github/workflows/*.yml -type f -execdir echo '{}' ';'    
    - name: deploy
      run: echo "Deploying the code - HELLO WORLD"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: my-artifact
        path: ${{ github.workspace }}
  print:
    uses: ./.github/workflows/reusable.yml


  
