name: Test REST API

on:
  push:
    branches: 
      - 'main'
    paths:
      - '**/test-api.yml'
      - '**.sh'
      
env:
    GH_TOKEN: ${{ github.token }}

permissions: read-all
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    
    - name: Run script (List Code Scanning Alerts for a Repo)
      run: bash ./myscript.sh
        # chmod=+x ./myscript.sh
        # ./myscript.sh
